### ISSUE TITLE
DO YOU SUPPORT IPV6?

### ISSUE THREAD

**Issue by ghost** [aold619/ocserv#5]
DO YOU SUPPORT IPV6?

**Comment by PandaRyshan** [comment]
Not yet. I'll add ipv6 config and release it later.

**Comment by PandaRyshan** [comment]
IPv6 works now, welcome to try and test. 

Please note, if you run ocserv on an IPv6 only server, then you only can access IPv6 server or website. And you can only use IPv6 address to SSH login on your server.
