### ISSUE TITLE
Request to add variables without external config

### ISSUE THREAD

**Issue by LumineRose** [aold619/ocserv#6]
Is it possible to add the ability to immediately use options and their values in the container without creating an external configuration file ?
camouflage = false
camouflage_secret = “thegreatwall”
cisco-client-compat = false

**Comment by PandaRyshan** [comment]
I don't understand. These variables you provided are the default value in my code.

I mean, if you don't provide an additional configuration file, a default configuration file will be created when the container starts, and it will contain these values. If you see unexpected behavior, please let me know.

**Comment by LumineRose** [comment]
I apologize, perhaps the translation is incorrect
I mean that at the moment it is not possible to edit these variables without creating config a local directory
I would like to be able to change their values directly in the container without creating additional files

**Comment by PandaRyshan** [comment]
I see.

First, comment or delete these lines in your docker-compose file to ensure the container doesn't generate any external files.

[docker-compose.yml.sample](https://github.com/PandaRyshan/ocserv/blob/12e9cf4babd01f6cd508b9e60856685d10660536/docker-compose.yml.sample#L18-L21)

    # volumes:
    #   - ./config:/etc/ocserv
    #   - ./letsencrypt:/etc/letsencrypt
    #   - <your-cloudflare-dns-conf>:/etc/ocserv/cloudflare.ini
    
Second, this image is built based on Ubuntu and the default user is root, so you can install any editor you like with `apt` command in the container, and change ocserv settings with the editor.

Run this cmd from your host shell to enter the container bash shell. For example your container name is 'ocserv':

```bash
docker exec -it ocserv bash
```

Run following cmd from the bash shell inside the container to install an editor, if you want use vim or other editor, you can replace `nano` with other name:

```bash
apt update && apt install nano -y

nano /etc/ocserv/ocserv.conf
```

Last, restart ocserv service from inside of container:

```bash
systemctl restart ocserv
```

Or `exit` from container and restart the container or compose:

```bash
docker restart ocserv
```

or

```bash
docker compose restart ocserv
```

**Comment by LumineRose** [comment]
If not difficult please tell me why server in container can restart cyclically. 
The configuration docker-compose.yml is exactly as specified in the example (only domain login and password are different).
I thought it might be os, just installed new ubuntu 22.04 did the same steps and I see the same cyclic reboots, can you tell me if there is any way to find out the exact cause?

Creating ocserv ... done
root@condemned-weight:~/ocserv# docker-compose ps
 Name               Command               State                  Ports
--------------------------------------------------------------------------------------
ocserv   /entrypoint.sh ocserv -c / ...   Up      0.0.0.0:443->443/tcp,:::443->443/tcp
root@condemned-weight:~/ocserv# docker-compose ps
 Name               Command               State                  Ports
--------------------------------------------------------------------------------------
ocserv   /entrypoint.sh ocserv -c / ...   Up      0.0.0.0:443->443/tcp,:::443->443/tcp
root@condemned-weight:~/ocserv# docker-compose ps
 Name               Command               State                  Ports
--------------------------------------------------------------------------------------
ocserv   /entrypoint.sh ocserv -c / ...   Up      0.0.0.0:443->443/tcp,:::443->443/tcp
root@condemned-weight:~/ocserv# docker-compose ps
 Name               Command                 State      Ports
------------------------------------------------------------
ocserv   /entrypoint.sh ocserv -c / ...   Restarting

**Comment by LumineRose** [comment]
Yes, that solved the problem, thanks for your help.
But there is a new problem, if it's not too much trouble, please help me: clients don't see each other in the local network/ no pinging/no connecting to each other via internal addresses (used to use wg for this) how to properly configure the docker container to make this possible

**Comment by PandaRyshan** [comment]
Are you using a windows Anyconnect client?

Windows Defender Firewall disables ICMP inbound requests by default. You can open "Control Panel" -> "System and Security" -> "Windows Defender Firewall" -> "Advanced Settings". You will see a new window "Windows Defender Firewall with Advanced Security". Click "Inbound Rules" on the left, and find "File and Printer Sharing (Echo Request - ICMPv4-In)" and "File and Printer Sharing (Echo Request - ICMPv6-In)" on the right. Use the Shift key to select these four rules and right click, Enable these 4 rules.

Now try to ping the Anyconnect client address with the ICMP rules enabled. It should be work.

If you're using linux, you could check "/etc/sysctl.conf" or configs in "/etc/sysctl.d/", to find is there an option `net.ipv4.icmp_echo_ignore_all = 1`. If the option exist, change the value to 0, and use command `sudo sysctl --system` to apply.
